### ISSUE TITLE
Any chance of seeing jwebunit 3.3 soon?

### ISSUE THREAD

**Issue by caspark** [JWebUnit/jwebunit#1]
Firstly, I apologise for using Github issues as a glorified contact form.

Anyway, it would be very helpful to have a release of jwebunit with support for htmlunit 2.18, because earlier releases of htmlunit (e.g. htmlunit 2.15 with jwebunit 3.2) do not work with version 4.4.x or higher of apache httpcomponents' httpclient version, yet newer versions of htmlunit do not work with jwebunit 3.2.

That unfortunately makes jwebunit the bottleneck for upgrading httpcomponents.

(I did see [mention of a 3.3-SNAPSHOT release](http://sourceforge.net/p/jwebunit/mailman/jwebunit-development/?viewmonth=201507) but we need our builds to be reproducible.)

**Comment by caspark** [comment]
As a datapoint as to whether the snapshot contains any breaking changes (or bugs), I ran our 1500+ jwebunit tests on a branch build with that branch upgraded to jwebunit 3.3-SNAPSHOT, htmlunit 2.18, and httpcomponents httpclient 4.5, and all the tests passed.

**Comment by henryju** [comment]
Sorry for the late notice. I'll take care of the release ASAP.

**Comment by henryju** [comment]
Release done.
